apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
spec:
  containers:
    - name: jnlp
      image: jenkins/inbound-agent:latest
    - name: docker
      image: docker:latest
      command: ["sleep", "infinity"]  # Example command, adjust as needed
      volumeMounts:
        - name: docker-socket
          mountPath: /var/run/docker.sock
